#!/bin/sh
#
# Copyright (C) 2021 Morse Micro Pty Ltd. All rights reserved.
#

. /morse/scripts/morse_init.sh

start()
{
    #/etc/init.d/S80dnsmasq stop
    #/etc/init.d/S41dhcpcd stop

    if ! parse_config; then
        echo "MORSE INIT - Invalid configuration, stopping" | tee /dev/kmsg
        start_ip_routing
        exit 1
    fi

    # Set console level to keep external displays clean
    dmesg -n 6

    #echo "MORSE INIT - Resetting MM chip" | tee /dev/kmsg
    #/morse/scripts/chipreset.sh

    #echo "MORSE INIT - Reading chip debug prints into /var/log/ttyAMA1.log" | tee /dev/kmsg
    #stty -F /dev/ttyAMA1 115200
    #cat /dev/ttyAMA1 >> /var/log/ttyAMA1.log &

    #echo "MORSE INIT - Initializing watchdog" | tee /dev/kmsg
    #watchdog -T 15 -t 5 /dev/watchdog

    if [ -n "$COUNTRY" ]; then
        echo "MORSE INIT - Inserting morse driver $MOD_PARAMS" | tee /dev/kmsg
        #modprobe spi-bcm2835
        #modprobe mac80211 beacon_loss_count=150
        /work/morse/install_morse.sh

        # Set HaLow MAC address
        local MAC_FIRST_3_PATTERN='[a-z0-9]\+\:[a-z0-9]\+\:[a-z0-9]\+'
        HALOW_MAC_ADDR=`cat /sys/class/net/eth0/address | sed "s/$MAC_FIRST_3_PATTERN/0c:bf:74/"`
        ifconfig $HALOW_IFACE down
        ifconfig $HALOW_IFACE hw ether $HALOW_MAC_ADDR

        # Enable RTS/CTS
        PHY_LIST=`iw list | grep 'phy[0-9]' | awk '{print $2}'`
        for PHY in $PHY_LIST;
        do
            echo "MORSE INIT - Enabling RTS/CTS on $PHY" | tee /dev/kmsg
            iw $PHY set rts 1000

            # Hook red LED to awlays on
            # echo ${PHY}assoc > /sys/class/leds/led0/trigger
            echo default-on > /sys/class/leds/led1/trigger
            # Hook green LED to TX trigger
            echo ${PHY}tx > /sys/class/leds/led0/trigger
        done

        # This sleep is essential
        sleep 2

	rfkill unblock wifi

        # Bring up interfaces
        ifconfig $HALOW_IFACE up
    fi
    ifconfig $ETH_IFACE   up

    # Do initialization based on mode
    case $MODE in
        ap)
            start_bridge
            if [ -n "$COUNTRY" ]; then
                start_ap
            fi
            start_ip_routing
            ;;
        sta)
            start_bridge
            if [ -n "$COUNTRY" ]; then
                start_sta
                # Make sure the connection is established before DHCP request is made
                if [ $HALOW_IP_METHOD -eq 2 ]; then
                    sleep 4
                fi
            fi
            start_ip_routing
            ;;
        wnm-sta)
            # Bridge mode not supported in this mode
            BRIDGE=0
            # Disable crash detection script
            /etc/init.d/S90crond stop
            # Stop ntp service
            /etc/init.d/S49ntp stop
            if [ -n "$COUNTRY" ]; then
                start_sta
                # Make sure the connection is established before DHCP request is made
                if [ $HALOW_IP_METHOD -eq 2 ]; then
                    sleep 4
                fi
            fi
            start_ip_routing
            ;;
        *)
            # Unspecified state, don't run AP or STA
            echo "MORSE INIT - WARNING: WLAN mode is NOT set" | tee /dev/kmsg
            start_bridge
            start_ip_routing
            ;;
    esac

    echo "MORSE INIT - IP addresses:" | tee /dev/kmsg
    if [ $BRIDGE -eq 1 ]; then
        ifconfig br0 | head -n 2 | tee /dev/kmsg
    else
        ifconfig $ETH_IFACE   | head -n 2 | tee /dev/kmsg
        ifconfig $HALOW_IFACE | head -n 2 | tee /dev/kmsg
    fi

    # Do not start web GUI when we are in wnm-sta mode
    if [ "$MODE" != "wnm-sta" ]; then
        if [ -z "`pidof uhttpd`" ]; then
            /usr/bin/uhttpd -p 80 -h /www -I morse.php -S -D -i .php=/usr/bin/php-cgi
        fi

        if [ -z "`pidof shellinaboxd`" ]; then
            shellinaboxd -c /tmp -u root -t -b --css=/www/white-on-black.css
        fi
    else
        echo "MORSE STOP - Stopping shellinaboxd and uhttpd" | tee /dev/kmsg
        kill_wait shellinaboxd uhttpd &> /dev/null
    fi

    #mount -t debugfs none /sys/kernel/debug
}

stop()
{
    parse_config

    echo "MORSE STOP - Stopping DHCP servers and clients" | tee /dev/kmsg
    kill_wait dnsmasq udhcpc &> /dev/null

    echo "MORSE STOP - Stopping hostapd_s1g and wpa_supplicant_s1g" | tee /dev/kmsg
    kill_wait hostapd_s1g wpa_supplicant_s1g &> /dev/null

    echo "MORSE STOP - $HALOW_IFACE down" | tee /dev/kmsg
    ifconfig $HALOW_IFACE down

    echo "MORSE STOP - Killing chip debug read"
    local output=`ps`
    if printf "$output" | grep -qE 'cat /dev/ttyAMA1';then
        kill `printf "$output" | grep 'cat /dev/ttyAMA1' | awk '{print $1F}'`
    fi

    echo "MORSE STOP - Removing HaLow drivers" | tee /dev/kmsg
    /morse/scripts/reset.sh

    umount /sys/kernel/debug
}

restart()
{
    stop
    start
}

case "$1" in
    stop)
        stop
        ;;
    start)
        start
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
