[dev]
ToFPath = "/dev/ttyS3"

[nnm]
ModelPath = "nef/yolov5_211_model_730.nef"
JobId = 11                              # for application switch
CameraPath = "/dev/video0"
#ImageWidth = 480
#ImageHeight = 640
ImageWidth = 1920
ImageHeight = 1080
Fps = 15

[venc]
enable_write = 0 # save encoded data to file
codec_type = 0 # 0: h.264, 1:h.265
ssm_reader_pin = vsrc_0_ifp_0
srb_writer_pin = venc_srb_1

# if need to resize stream to desired size.
#Resize_Width = 640
#Resize_Height = 480
